### ISSUE TITLE
Ontology file format

### ISSUE THREAD

**Issue by kwalcock** [clulab/eidos#322]
This is extending PR #311. I decided to make it an issue, even though it may be difficult to find.

**Comment by kwalcock** [comment]
Regarding WDI and the duplicate paths...

```
- WDI: # old WDI ontology
  - 2005_PPP_conversion_factor:
    - description:
      - "GDP (LCU per international $)"
  - 2005_PPP_conversion_factor:
    - description:
      - "private consumption (LCU per international $)"
```
On these the paths are often duplicated, but the descriptions are different.  At one point (IIRC) the code threw these into a set based on path and then extracted them.  This resulted in a loss of some of the descriptions.  I believe that the grounding is intended to be based on those potentially lost descriptions.  As we make the paths unique, should the descriptions somehow be combined so that they can all be used, something like this (ignore the syntax which is going to change):

```
- WDI: # less old WDI ontology
  - 2005_PPP_conversion_factor:
    - description(s):
      - "GDP (LCU per international $)"
      - "private consumption (LCU per international $)"
```

**Comment by kwalcock** [comment]
Regarding the IDs...  I'm not sure where they came from or what they are intended to do.  Are they supposed to be unique within an ontology, between our ontologies, between ontologies built by anyone?  At some point we started adding a top level to the path (-UN:, -FAO:, -WDI:).  This in combination with the remaining unique path gives us uniqueness across at least our ontologies.  This ID is so far never output anywhere.  Is the ID supposed to just be shorter than the entire path or a simple way to search in the file for an entry (difficult in a tree)?  Can we just call them UN1, UN2, UN3, etc.?  If we edit an ontology, our IDs probably won't be consistent across different versions of it.  An insertion or deletion would mess things up.  UN200 would be "foo" in version 1 of the ontology and may be "bar" in version 2.  Maybe that doesn't matter.  I wonder whether the ID will be used whatsoever.  Any advice?

**Comment by kwalcock** [comment]
And just for completeness, we have at least "examples" and "descriptions".  These will not be generalized into "texts" or "values" or something, because "descriptions" is our trigger to perform filtering on POS.  Rather than indicate this at every single node, assuming all nodes are the same in the ontology, this could be indicated at some higher level.  In that case, the branch for field ("texts", "values", etc.) could disappear.  Then probably someone will have an entry with both examples and descriptions and mess it up.  So, keep it?  BTW our code does not very well account for the words "examples" and "descriptions" being potential parts of the path.  Should we be escaping in some way?

```
- UN: # old UN ontology
  - events:
    - nature_impact:
      - positive_nature_impact:
        - examples:
          - conservation
          - sustainable use
```

**Comment by MihaiSurdeanu** [comment]
- I agree that duplicated nodes should be merged, and the corresponding descriptions be merged into a "descriptions" array.
- Please see my slide about the new format. "examples" and "descriptions" should NOT be part of this path, but rather be fields in the OntologyNode class. @kwalcock, @ZhengTang1120: Please let me know if this is clear. @kwalcock: I would like to see a JSON that encodes a toy ontology in this format, as we discussed yesterday. Can you please paste it here?

**Comment by kwalcock** [comment]
Do you mean YAML format instead?  So far, all input to Eidos is YAML and output is JSON.

**Comment by MihaiSurdeanu** [comment]
Sorry, I meant YAML!

**Comment by kwalcock** [comment]
The old "toy" ontology gets a top level and "examples" so that it doesn't have to use "others" that was seen in the code.  Maybe there's an ID.
```
- events: # old "toy" ontology
  - crisis:
    - "crisis"
    - "emergency"
  - natural:
    - weather:
      - precipitation:
        - "precipitation"
        - "rain"

-TOY: # new "toy" ontology
  - events:
    - crisis:
      id: ???
      examples:
        - "crisis"
        - "emergency"
    - natural:
      - weather:
        - precipitation:
          id: ???
          examples:
            - "precipitation"
            - "rain"
```

**Comment by kwalcock** [comment]
Not much is changed for UN except a "-" if I understand the syntax correctly.
```
- UN: # old UN ontology
  - events:
    - nature_impact:
      - positive_nature_impact:
        - examples:
          - conservation
          - sustainable use
          - afforestation
          - agroforestry
      - negative_nature_impact:
        - examples:
          - pollution
          - deforestation
          - soil erosion
          - desertification

- UN: # new UN ontology
  - events:
    - nature_impact:
      - positive_nature_impact:
        id: ???
        examples:
          - conservation
          - sustainable use
          - afforestation
          - agroforestry
      - negative_nature_impact:
        id: ???
        examples:
          - pollution
          - deforestation
          - soil erosion
          - desertification
```

**Comment by kwalcock** [comment]
FAO only ever had one description, but since WDI can have multiple, it is a list here.  FAO has not used _ instead of spaces for node labels, unlike the other files.  We should pick one way or the other.  We could make use of this and call our things _examples and _descriptions.

```
- FAO: # old FAO ontology
  - events:
    - Agriculture orientation index:
      - Gross Fixed Capital Formation (Agriculture, Forestry and Fishing):
        - description:
          - "Agriculture orientation index Gross Fixed Capital Formation (Agriculture, Forestry and Fishing)"
      - DFA Commitment to Agriculture, Forestry and Fishing:
        - description:
          - "Agriculture orientation index DFA Commitment to Agriculture, Forestry and Fishing"

- FAO: # new FAO ontology
  - events:
    - Agriculture orientation index:
      - Gross Fixed Capital Formation (Agriculture, Forestry and Fishing):
        id: ???
        descriptions: 
          - "Agriculture orientation index Gross Fixed Capital Formation (Agriculture, Forestry and Fishing)"
      - DFA Commitment to Agriculture, Forestry and Fishing:
        id: ???
        descriptions:
          - "Agriculture orientation index DFA Commitment to Agriculture, Forestry and Fishing"
```

**Comment by kwalcock** [comment]
Duplicate descriptions are combined for WDI.
````
- WDI: # old WDI ontology
  - 2005_PPP_conversion_factor:
    - description:
      - "GDP (LCU per international $)"
  - 2005_PPP_conversion_factor:
    - description:
      - "private consumption (LCU per international $)"
  - Access_to_clean_fuels_and_technologies_for_cooking__(%_of_population):
    - description:
      - "Access to clean fuels and technologies for cooking is the proportion of total population primarily using clean cooking fuels and technologies for cooking. Under WHO guidelines"

- WDI: # new WDI ontology
  - 2005_PPP_conversion_factor:
    id: ???
    descriptions:
      - "GDP (LCU per international $)"
      - "private consumption (LCU per international $)"
  - Access_to_clean_fuels_and_technologies_for_cooking__(%_of_population):
    id: ???
    descriptions:
      - "Access to clean fuels and technologies for cooking is the proportion of total population primarily using clean cooking fuels and technologies for cooking. Under WHO guidelines"
````
