### ISSUE TITLE
Ontology branches should support leaf node values

### ISSUE THREAD

**Issue by kwalcock** [clulab/eidos#972]
Here's some documentation of a less than optimal decision I had to make at least temporarily.  The InnerOntologyNode below would (slightly?) better be called an OntologyNode, which it is further below with the leaf node for livestock_feed.  The problem is that our yaml library is weird plus if the code were to see OntologyNode after concept, it would think it was at a leaf node already and not look further to causal_factor to figure out it was actually a branch.  In addition, this InnerOntologyNode doesn't need a name, because the name is already given for the branch, so it's not really the same as the OntologyNode.  It seems possible that someone would try to apply multiple (Inner)OntologyNodes to a branch, and that should not be possible, even though it is possible to do that at the end of the branch.  The parser is expecting at most one InnerOntologyNode and it must be the very first child.

For reasons of compatibility with humans and other code bases I'm [included => meaning inclined] to have two things named OntologyNode.  If attached to the middle of a branch, it will not have a name and is limited to one instance (which can hopefully appear anywhere).  If attached to the end of a branch, it does have a name and can appear multiple times.

```yaml
- wm:
  - concept:
    - InnerOntologyNode:
      examples:
      - buckle my shoe
      - shut the door
      - pick up sticks
      neg_examples:
      - hiep
      - hiep
      - hoera
    - causal_factor:
      - interventions:
        - provide: # (supply, distribute, deliver, vaccinate, give)
          - agriculture_inputs: # agricultural_productivity
            - livestock_production_inputs:
              - OntologyNode:
                examples:
                - livestock feed
                - hay
                - CSB
                - silage
                - corn meal
                - soybean hulls
                neg_examples:
                - one
                name: livestock_feed
```

**Comment by MihaiSurdeanu** [comment]
@kwalcock: I don't understand this sentence: "The parser is expecting at most one InnerOntologyNode and it must be the very first child." We should allow such nodes to appear on any non-leaf node in a branch, which, of course, can be more than one...

**Comment by kwalcock** [comment]
I expressed that poorly and will again.  Each non-terminal branch node, so something with a name and perhaps multiple subbranches and leaves with their own names, can have a leaf or leaf-like information, but only one, because that node only has one name which will be given to the leaf.  Although it is syntactically possible to have multiple leaves there (or sets of leaf information), they'd all have the same name and it wouldn't make sense.

There are other ways to do it, like allowing a leaf to have children, making it a more generic node.  That might be disruptive. but maybe a good thing.

Our abbreviated syntax with some nodes being described only by name is complicating things.  We might end up with a pair like

this/that which is a branch "this" with a leaf "that", and
this/that/ which is a branch "this", and branch "that" with leaf information attached to "that"
this/that/more which is a "more" leaf attached to "this/that/", which is why "that/" needed to be a branch, because leaf "this/that" doesn't support child leaves presently.

Leaves and branches would more or less have different namespaces, as if in a filesystem the name of a file and directory could be the same.

**Comment by MihaiSurdeanu** [comment]
Thanks @kwalcock!
- I think it's fine if we only one meta data structure per node.
- Allowing leaves to have children might be more elegant, but I'm not sure how disruptive it is. What do you think?
- Agree with the different namespaces for leaves and non-terminals.

**Comment by kwalcock** [comment]
We've recently even been discussing changing to JSON format to be able to add data to the non-leaf nodes.  The example above shows how to make a reserved list item called InnerOntologyNode here and add it to the list of children of non-leaf nodes.  The other way is to turn each non-leaf node into a dictionary which would hold the metadata and to put the list of children in a field.  An example is below with metadata for wm and the lists placed under the key "children".  This is neater, but more invasive, because "children" is required everywhere.

```yaml
- wm:
  examples:
  - crime
  definition:
  polarity: -1
  semantic type: event
  children: 
  - concept:
    children:
    - agriculture:
      children:
      - crop:
        children:      
        - cereals:
          examples:
          - maize
          definition: A grass cultivated for the edible parts of its grain.
          polarity: 1
          semantic type: entity
        - vegetables:
          examples:
          - vegetables
          definition: vegetable crops and food
          polarity: 1
          semantic type: entity
    - crisis_or_disaster:
      children:      
      - conflict:
        children:      
        - crime:
          examples:
          - crime
          definition:
          polarity: -1
          semantic type: event
        - hostility:
          examples:
          - skirmish
          definition:
          polarity: -1
          semantic type: event

```

**Comment by kwalcock** [comment]
In the first proposed format in which everything is a list with one reserved name, the InnerOntologyNode and OntologyNode can probably be combined into one thing if the parser was made slightly smarter and looked ahead a little to check for children.  It would just disrupt existing code a little more.

Although I don't especially like YAML, it does well in connecting parents to children without either of them being named and therefore no link rot in which a change in parent or child name is not propagated to names at the other end of the arrow.  On the other hand, it is difficult to move up and down the long file and keep track of indentation.  On this kind of file I'd be inclined to try 4 spaces instead of 2.

JSON example to follow...

**Comment by kwalcock** [comment]
The JSON can be nested as well, but because of the trailing braces it's a little difficult to move things around.  If not nested, then references are required, like this:
```json
[
  {
     "name": "wm",
     "examples": ["crime"],
     "definition": "",
     "polarity": -1,
     "semantic_type": "entity"
  },
  {
    "name": "wm/concept"
  },
  {
    "name": "wm/concept/agriculture"
  },
  {
    "name": "wm/concept/agriculture/crop"
  },
  {
    "name": "wm/concept/agriculture/crop/cereals",
    "examples": ["maize"],
    "definition": "A grass cultivated for the edible parts of its grain.",
    "polarity": 1,
    "semantic_type": "entity"    
  },
  {
    "name": "wm/concept/agriculture/crop/vegetables",
    "examples": ["vegetables"],
    "definition": "vegetable crops and food",
    "polarity": 1,
    "semantic_type": "entity"
  },
  {
    "name": "wm/concept/crisis_or_disaster"
  },
  {
    "name": "wm/concept/crisis_or_disaster/crime",
    "examples": ["crime"],
    "definition": "",
    "polarity": -1,
    "semantic_type": "event"
  },
  {
    "name": "wm/concept/crisis_or_disaster/hostility",
    "examples": ["skirmish"],
    "definition": "",
    "polarity": -1,
    "semantic_type": "event"
  }  
]
```
In this case the name is the entire path.  Instead, there could be a unique ID (number) for each node to which children could refer and the name would only be the incremental part.  That leaves humans matching up numbers, which is difficult, but it might be better than figuring out what happens when "concept" changes to "idea" and needs to be updated everywhere.

**Comment by kwalcock** [comment]
@MihaiSurdeanu and @BeckySharp, we were talking about formats this morning.  Everyone seemed dissatisfied with the current format, but maybe that's just because of the missing data on parents rather than the yaml.  There are a couple of ideas above.  Right now I like the very first the best but with InnerOntologyNode and OntologyNode unified into "metadata" or "node" or something.

**Comment by BeckySharp** [comment]
OK, so i was delaying replying to this bc I thought at the meeting would be
a good time, but now I won't be at the meeting :)
So......

I was pretty convinced about the yaml argument re: not having to sed to
replace things if you make a change.
Given yaml, I vote:

   - for readability 4 spaces is better than 2
   - "children" should ideally be the last key, since it opens a new drop
   down

also, for something like this:

- vegetables:
  examples:
  - vegetables
  definition: vegetable crops and food
  polarity: 1
  semantic type: entity

which I take to be an entry in a list, the entry is a dictionary, with the
keys "vegetables", "examples", "definition", ...
and the _value_ for the "vegetables" key is None?

can we alter it to :

- name: vegetables
  examples:
  - vegetables
  definition: vegetable crops and food
  polarity: 1
  semantic type: entity

so that the keys are always the same? and there are no sneaky Nones that
need to be reworked in python to dump an empty string?

thoughts?

**Comment by MihaiSurdeanu** [comment]
This sounds good to me. But I will defer to @kwalcock on the feasibility of this representation.

**Comment by kwalcock** [comment]
There are two vegetables.  I *think* the value for the first vegetables key is a dictionary with its own keys of examples, definition, etc. rather than None, but it might depend on the library.  The value for the second vegetables might be None.

@BeckySharp, yes, that's a version from my example file not provided just because it involved a few more changes to the current format than other versions.  It is probably easier to process with certain libraries if the keys are all known in advance (no first vegetables) and the computer doesn't have to take the list of children and ask for their keys.  Humans, on the other hand, don't seem to have a problem with it, so I hope they don't mind helping out the computer with some redundancy.  It may be that your example needs an extra thing at the tops as a sort of placeholder or confirmation that everything is indeed a node and not something else, like

```yaml
- Node:
    name: wm
    examples:
        - crime
    definition:
    polarity: -1
    semantic type: event
    children: 
        - Node:
            name: concept
            examples:
                - crime
            definition:
```
Here crime would have no value.  This is formatted with 4 spaces with both list items and dictionary keys all indented, which gets a little wide in a short example, but maybe it's better in very long files.

**Comment by BeckySharp** [comment]
I like this, and I like that the sub things are indented from `Node`
meaning that they are key/value pairs in a dict, which itself is the value
of "Node:"

**Comment by kwalcock** [comment]
The capital Node was there to preserve the traditional capitalization of OntologyNode and then the InnerOntologyNode.  However, since they are gone, I'd make all keys lowercase as such:
```yaml
- node:
    name: wm
    examples:
        - crime
    definition:
    polarity: -1
    semantic type: event
    children: 
        - node:
            name: concept
            examples:
                - crime
            definition:
```
